server:
  port: 8080
javax:
  sql:
    DataSource:
      helidonTxTestDataSource:
        dataSourceClassName: oracle.jdbc.pool.OracleDataSource
        username: helidon
        password: helidon
        dataSource:
          url: jdbc:oracle:thin:@localhost:1521/ORCLPDB1
