server:
  port: 8080
javax:
  sql:
    DataSource:
      helidonTxTestDataSource:
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        username: helidon
        password: helidon
        dataSource:
          url: jdbc:h2:~/devel/h2/helidon
