server:
  port: 8080
oracle:
  ucp:
    jdbc:
      PoolDataSource:
        helidonTxTestDataSource:
          connectionFactoryClassName: oracle.jdbc.pool.OracleDataSource
          URL: jdbc:oracle:thin:@localhost:1521/ORCLPDB1
          user: helidon
          password: helidon
